Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.define "server" do |web_config|
    web_config.vm.synced_folder "./php", "/var/www/php", type: "virtualbox"
    web_config.vm.synced_folder "./html", "/var/www/html", type: "virtualbox"

    # Виртуальная машина для HTML-сервера (порт 8080)
    web_config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true

    # Виртуальная машина для PHP-сервера (порт 8081)
    web_config.vm.network "forwarded_port", guest: 81, host: 8081, auto_correct: true

    # Настройка Apache2 и создание виртуальных хостов
    web_config.vm.provision "shell", inline: <<-SHELL
      # Установка Apache и PHP
      apt-get update
      apt-get install -y apache2 php
      service apache2 restart

      # Добавляем порт 81 в прослушиваемый
      sed -i 's/Listen 80/Listen 80\\nListen 81/' /etc/apache2/ports.conf

      # Копирование файлов конфигурации для Apache
      cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/php.conf
      cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/html.conf

      # Настройка виртуальных хостов для HTML
      sh -c 'echo "<VirtualHost *:80>
           ServerName localhost
           DocumentRoot /var/www/html
        </VirtualHost>" > /etc/apache2/sites-available/000-default.conf'

      # Настройка виртуальных хостов для PHP
      sudo sh -c 'echo "<VirtualHost *:81>
            DocumentRoot /var/www/php
            DirectoryIndex index.php
            <Directory /var/www/php>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Require all granted
            </Directory>
        </VirtualHost>"  > /etc/apache2/sites-available/php.conf'

      a2ensite 000-default.conf
      a2ensite php.conf

      # Перезапуск Apache
      service apache2 restart
    SHELL

  end
end
