Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"

  config.vm.provider "virtualbox" do |vb|
#       vb.name = "debian11.vagrant.vm"
      vb.memory = "512"
  end

   config.vm.synced_folder "./php", "/var/www/php"
   config.vm.synced_folder "./html", "/var/www/html"


   # Виртуальная машина для HTML-сервера (порт 8080)
  config.vm.network "forwarded_port", guest: 80, host: 8080,
    auto_correct: true

  # Виртуальная машина для PHP-сервера (порт 8081)
  config.vm.network "forwarded_port", guest: 80, host: 8081,
    auto_correct: true

  # Настройка Apache2 и создание виртуальных хостов
  config.vm.provision "shell", inline: <<-SHELL
    # Установка Apache и PHP
    apt-get update
    apt-get install -y apache2 php libapache2-mod-php
    service apache2 restart

    # Создание каталога для HTML-сервера
    mkdir /var/www/html

    # Создание каталога для PHP-сервера
    mkdir /var/www/php

    # Настройка прав доступа
    chown -R vagrant:vagrant /var/www/html
    chown -R vagrant:vagrant /var/www/php

    # Копирование файлов конфигурации для Apache
    cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/html.conf
    cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/php.conf

    # Настройка виртуальных хостов для HTML и PHP
    sed -i 's/80/8080/' /etc/apache2/sites-available/html.conf
    sed -i 's/80/8081/' /etc/apache2/sites-available/php.conf

    # Активация виртуальных хостов
    a2ensite html.conf
    a2ensite php.conf

    # Перезапуск Apache
    service apache2 restart
  SHELL

end

