Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"

  config.vm.provider "virtualbox" do |vb|
#       vb.name = "debian11.vagrant.vm"
      vb.memory = "512"
  end
  config.vm.define "server" do |web_config|
    web_config.vm.synced_folder "./php", "/var/www/php", type: "virtualbox"
    web_config.vm.synced_folder "./html", "/var/www/html", type: "virtualbox"


    # Виртуальная машина для HTML-сервера (порт 8080)
    web_config.vm.network "forwarded_port", guest: 80, host: 8080,
      auto_correct: true

    # Виртуальная машина для PHP-сервера (порт 8081)
    web_config.vm.network "forwarded_port", guest: 81, host: 8081,
      auto_correct: true

    # Настройка Apache2 и создание виртуальных хостов
    web_config.vm.provision "shell", inline: <<-SHELL
      # Установка Apache и PHP
      apt-get update
      apt-get install -y apache2 php libapache2-mod-php
      service apache2 restart

      # Настройка прав доступа
      chown -R vagrant:vagrant /var/www/html
      chown -R vagrant:vagrant /var/www/php

      # Добавляем порт 81 в прослушиваемый
      sed -i '/Listen 80/a\Listen 81/' /etc/apache2/ports.conf

      # Настройка виртуальных хостов для HTML и PHP
      echo "<VirtualHost *:80>
        ServerName localhost
        DocumentRoot /var/www/html
      </VirtualHost>" | tee /etc/apache2/sites-available/000-default.conf

      echo "<VirtualHost *:80>
        ServerName localhost
        DocumentRoot /var/www/php
        <Directory /var/www/php>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>
      </VirtualHost>" | tee /etc/apache2/sites-available/php.conf

      a2ensite php.conf
      a2ensite 000-default

      # Перезапуск Apache
      systemctl reload apache2

    SHELL
  end
end
