services:
  jenkins:
    build:
      context: ./Path
      dockerfile: Dockerfile_jenkins
    ports:
      - "8080:8080"
      - "80:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    networks:
      - cicd_network

  nexus:
    build:
      context: ./Path
      dockerfile: Dockerfile_nexus
    ports:
      - "8081:8081"
      - "81:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - cicd_network

volumes:
  jenkins_home:
    external: true
    name: jenkins_home
  nexus_data:
    external: true
    name: nexus_data

networks:
    cicd_network:
        driver: bridge