FROM jenkins/jenkins

ENV JENKINS_USER admin
ENV JENKINS_PASS admin

ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

COPY plugins.txt /usr/share/jenkins/plugins.txt
COPY jenkins.yaml /var/lib/jenkins/casc_configs/jenkins.yaml
COPY config.xml /var/lib/jenkins/jobs/pipeline/config.xml

RUN /usr/local/bin/install-plugins.sh < usr/share/jenkins/plugins.txt

USER root

RUN apt-get update  -qq \
    && apt-get install docker-ce -y

RUN usermod -aG docker jenkins
RUN apt-get clean

USER jenkins