---
- name: Install Puppet on Master
  hosts: master
  become: true
  gather_facts: false

  tasks:
    - name: Install Puppet Server and r10k on Master
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - puppetserver
        - git
      when: "'master' in inventory_hostname"

    - name: Add or modify JAVA_ARGS in puppet.conf
      lineinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        regexp: '^JAVA_ARGS='
        line: 'JAVA_ARGS="-Xms256m -Xmx256m"'
      notify:
        - Start Puppet Server

  handlers:
    - name: Start Puppet Server
      systemd:
        name: puppetserver
        state: started
        enabled: yes
      ignore_errors: true

- name: Install Puppet on Slaves
  hosts: slave*
  become: yes
  gather_facts: false

  tasks:
    - name: Install Puppet Agent and PHP on Slave
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - puppet-agent
        - httpd
        - php
        - git
      when: "'slave' in inventory_hostname"

    - name: Restart httpd
      service:
        name: httpd
        state: restarted
      when: "'slave' in inventory_hostname"
