---
- name: Install Puppet on Master and Slaves
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Install Puppet Server and r10k on Master
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - puppetserver
        - git
      notify:
        - start puppet server
      when: "'master' in inventory_hostname"

  handlers:
    - name: start puppet server
      systemd:
        name: puppetserver
        state: started
        enabled: yes
      ignore_errors: true

    - name: Install Puppet Agent and PHP on Slave
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - puppet-agent
        - httpd
        - php
        - git
      when: "'slave' in inventory_hostname"

    - name: Restart httpd
      service:
        name: httpd
        state: restarted
      when: "'slave' in inventory_hostname"
