---
- name: Master puppet
  hosts: master.puppet
  become: true

  tasks:
#    - name: Install the puppet rpm from a remote repo
#      yum:
#        name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
#        state: present

    - name: Install Puppet Server and r10k
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - puppetserver
        - puppet
        - git
      notify:
        - start puppet server

  handlers:
    - name: start puppet server
      systemd:
        name: puppetserver
        state: started
        enabled: yes

- name: Slaves
  hosts: slave1.puppet:slave2.puppet
  become: true

  tasks:
#    - name: install the puppet rpm from a remote repo
#      yum:
#        name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
#        state: present

    - name: Install Puppet Agent and PHP
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - puppet-agent
        - apache2
        - php
        - git

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
