# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.synced_folder  ".", "/vagrant", disabled: false

  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "192.168.50.70"
  config.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "192.168.50.75"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus   = 2
  end
  # Установка Docker
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y docker.io
    usermod -aG docker vagrant
    sudo systemctl enable docker
    sudo systemctl start docker
    cp -r /vagrant/simple /home/vagrant/simple
    cp -r /vagrant/multi /home/vagrant/multi
  SHELL
end
