---
- hosts: nginx
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Configure Nginx reverse proxy
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify:
        - restart Nginx

  handlers:
    - name: restart Nginx
      service:
        name: nginx
        state: restarted