service:
  port: 8888
  name: wcg-service

replicas: 1

container:
  port: 8888
  portName: http
  label: word-cloud-generator
  name: word-cloud-generator

image:
  repository: ghcr.io/viinsent/wcg
  tag: "latest"

ingress:
  host: word-cloud-generator.test.local
  path: /
  pathType: Prefix