---
- name: Nexus
  hosts: nexus
  become: yes
  vars_files:
    - vars.yml

  vars:
    nexus_admin_password: "{{ NEXUS_ADM_PASS }}"
    nexus_public_hostname: '{{ NEXUS_IP }}'
    nexus_anonymous_access: false
    nexus_delete_default_repos: true
    nexus_repos_raw_hosted:
      - name: word-cloud-build
        version_policy: release
        write_policy: allow_once  # one of "allow", "allow_once" or "deny"
    nexus_privileges:
      - name: nx-repository-view-raw-word-cloud-build-*
        description: 'All privileges for word-cloud-build repository views'
        repository: 'word-cloud-build'
        actions:
          - read
          - browse
    nexus_roles:
      - id: nx-uploader
        name: nx-uploader
        description: nx-uploader
        privileges:
          -  nx-repository-view-raw-word-cloud-build-*
        roles: []
    nexus_local_users:
      - username: "{{ NEXUS_USER }}"
        first_name: uploader
        last_name: nx
        email: nx-uploader@email.com
        password: "{{ NEXUS_PASS }}"
        roles:
          - nx-uploader
