Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.synced_folder  ".", "/vagrant", disabled: false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  config.vm.network "forwarded_port", guest: 81, host: 8081, auto_correct: true

  config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y mc ansible sshpass
  SHELL

  config.vm.provision "ansible_local" do |ansible|
      ansible.inventory_path = "inventory"
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "playbook.yaml"
      ansible.become = true
  end
end
