Vagrant.configure("2") do |config|
  config.vm.define "html_vm" do |html|
    html.vm.box = "generic/debian11"
    html.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    # Синхронизация папок
    html.vm.synced_folder "./html", "/var/www/html"

    # Виртуальная машина для HTML-сервера (ip 192.168.33.10)
    html.vm.network "private_network", ip: "192.168.33.10"

    # Установка и настройка Apache2
    html.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2
    SHELL

    # Изменение конфигурации файла 000-default.conf
    html.vm.provision "shell", inline: <<-SHELL
      sh -c 'echo "<VirtualHost *:80>
           ServerName 192.168.33.10
           DocumentRoot /var/www/html
        </VirtualHost>" > /etc/apache2/sites-available/000-default.conf'
      systemctl restart apache2
    SHELL
  end

  config.vm.define "php_vm" do |php|
    php.vm.box = "generic/debian11"
    php.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    # Синхронизация папок
    config.vm.synced_folder "./php", "/var/www/php"

    # Виртуальная машина для PHP-сервера (ip 192.168.33.12)
    php.vm.network "private_network", ip: "192.168.33.12"

    # Установка и настройка Apache2 и PHP
    php.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2 php
    SHELL

    # Копирование настроек файла 000-default.conf в файл php.conf
    php.vm.provision "shell", inline: <<-SHELL
       cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/php.conf
    SHELL

    # Изменение конфигурации файла php.conf
    php.vm.provision "shell", inline: <<-SHELL
      sh -c 'echo "<VirtualHost *:80>
            ServerName 192.168.33.12
            DocumentRoot /var/www/php
            DirectoryIndex index.php
            <Directory /var/www/php>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Require all granted
            </Directory>
        </VirtualHost>"  > /etc/apache2/sites-available/php.conf'

      a2ensite php.conf
      systemctl restart apache2
    SHELL

  end
end
