Vagrant.configure("2") do |config|
  config.vm.define "html_vm" do |html|
    html.vm.box = "generic/debian11"
    html.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    html.vm.synced_folder "./html", "/var/www/html"

    html.vm.network "forwarded_port", guest: 80, host: 8080
    html.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2
    SHELL

    html.vm.provision "shell", inline: <<-SHELL
      sh -c 'echo "<VirtualHost *:80>
           ServerName localhost
           DocumentRoot /var/www/html
        </VirtualHost>" > /etc/apache2/sites-available/000-default.conf'
      systemctl restart apache2
    SHELL
  end

  config.vm.define "php_vm" do |php|
    php.vm.box = "generic/debian11"
    php.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    config.vm.synced_folder "./php", "/var/www/php"

    php.vm.network "forwarded_port", guest: 81, host: 8081
    php.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2 php
    SHELL

    php.vm.provision "shell", inline: <<-SHELL
       sed -i 's/Listen 80/Listen 81/' /etc/apache2/ports.conf
       cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/php.conf
    SHELL

    php.vm.provision "shell", inline: <<-SHELL
      sh -c 'echo "<VirtualHost *:81>
            DocumentRoot /var/www/php
            DirectoryIndex index.php
            <Directory /var/www/php>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Require all granted
            </Directory>
        </VirtualHost>"  > /etc/apache2/sites-available/php.conf'

      a2ensite php.conf
      systemctl restart apache2
    SHELL

  end
end
