---
- name: Install and configure production
  hosts: production
  become: yes
  become_method: sudo

  tasks:
    - name: Add user
      user:
        name: jenkins
        password: "jenkins"

    - name: Copy system file
      copy:
        src: "{{ playbook_dir }}/templates/wordcloud.service"
        dest: /etc/systemd/system/

    - name: Create wordcloud directory
      file:
        state: directory
        path: /opt/wordcloud/

    - name: Change folder wordcloud owner
      file:
        path: /opt/wordcloud/
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'
