name: Word Cloud Generator
on: 
  push:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16  

    steps:
      - name: test step
        run: echo 'Hello World'

      - name: checout code
        uses: actions/checkout@v4
        with: 
          repository: ViinSent/word-cloud-generator

      - name: build wcg
        run: |
          make
          ls -la

      - name: Archive code coverge result
        uses: actions/upload-artefact@v3
        with:
          name: wcg_linux
          path: artefacts/linux/*
    
  upload:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: wcg_linux

      - name: test
        run: ls -la

    
        
    
    

