name: WCG from docker

on: 
  push:
  workflow_dispatch: 

env:
  IMAGE_NAME: "wcg"
  REGISTRY: "ghcr.io"
  HELM_REPO: "12-helm"
  CHART_NAME: "wcg"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: test
        run: ls -la

      - name: set lower case owner name
        run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git config --global user.email "viinsent@gmail.com"
          git config --global user.name ${{ github.actor }}
          echo TAG_NAME= "v.1.0" >> $GITHUB_ENV
          git tag -a v.1.0 -m "Tagging new version"
      
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker buildx create --use && docker buildx build -t ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest  -t ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f Dockerfile . --push
  
  helm:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Helm lint
        run: helm lint ${{ env.HELM_REPO }}

      - name: Package Helm chart
        run: helm package ${{ env.HELM_REPO }} -d ${{ env.HELM_REPO }}

      - name: Update Helm repository index
        run: helm repo index ${{ env.HELM_REPO }} --url https://github.com/ViinSent/viinsent.github.io.git
        
      - name: Create tag for main branch
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}

      # - name: Deploy Helm chart with Argo CD
      #   run: |
      #     argocd login <ARGOCD_SERVER> --username <USERNAME> --password <PASSWORD>
      #     argocd app create <APP_NAME> --repo <HELM_REPO_URL> --path <CHART_PATH> --dest-namespace <NAMESPACE> --dest-server https://kubernetes.default.svc --sync-policy auto
      #     argocd app set <APP_NAME> --values path/to/values.yaml
      #     argocd app sync <APP_NAME>
      #   env:
      #     ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
      #     USERNAME: ${{ secrets.ARGOCD_USERNAME }}
      #     PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
      #     APP_NAME: your-app-name
      #     HELM_REPO_URL: https://your-helm-repo-url.com
      #     CHART_PATH: path/to/your/chart
      #     NAMESPACE: your-namespace
