name: WCG from docker

on: 
  push:
  workflow_dispatch: 

env:
  IMAGE_NAME: "wcg"
  REGISTRY: "ghcr.io"
  HELM_REPO: "12-helm"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test
        run: ls -la

      - name: Set lower case owner name
        run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ env.IMAGE_NAME }} ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker buildx create --use && docker buildx build -t ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest -t ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }} -f Dockerfile . --push
                                                             # -t ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
  
      - name: Helm lint
        run: helm lint ${{ env.HELM_REPO }}

      - name: Update Chart Version
        run: |
          sed -i 's/version: v[0-9]*\.[0-9]*\.[0-9]*/version: ${{ steps.tag_version.outputs.new_tag }}/' 12-helm/Chart.yaml
          # Commit the changes
          git config --local user.email "viinsent@gmail.com"
          git config --local user.name ${{ github.actor }}
          git add 12-helm/Chart.yaml
          git commit -m "Update Chart version"
          git push

